PERSONALITY_NAME="vault-postgres"
PERSONALITY_TIER="vault"
PERSONALITY_TEMPLATE="zroot/jails/templates/vault-postgres@base"
PERSONALITY_PACKAGES="" # installed in template, not here
PERSONALITY_NEEDS_XPRA_DIR="no"
PERSONALITY_ENCRYPTED_DATA="yes"
PERSONALITY_DATA_MOUNT="/var/db/postgres/data"
PERSONALITY_DATA_SOURCE="/zroot/vault-data"
PERSONALITY_PROVISION="provision.sh"
PERSONALITY_INTERNAL_SERVICES="postgresql"
