PERSONALITY_NAME="vault-files"
PERSONALITY_TIER="vault"
PERSONALITY_TEMPLATE="zroot/jails/templates/vault-files@base"
PERSONALITY_PACKAGES=""
PERSONALITY_NEEDS_XPRA_DIR="no"
PERSONALITY_ENCRYPTED_DATA="yes"
PERSONALITY_DATA_MOUT="/var/vault-data"
PERSONALITY_DATA_SOURCE="/zroot/vault-data"
PERSONALITY_PROVISION="provision.sh"
PERSONALITY_INTERAL_SERVICES="sshd"
