ext_if = "vtnet0" # change to em0 when deploying to bare metal. or igb0 or re0. whatever NIC is used.
int_if = "bridge0"

# options
set skip on lo0
set skip on $int_if

# normalization
scrub in on $ext_if all fragment reassemble

# translation
nat on $ext_if from 10.0.0.0/24 to any -> ($ext_if)

# filtering
block all
block in quick on $ext_if
pass out quick on $ext_if
