vault-churchcrm {
	host.hostname = "vault-churchcrm.parishbsd.local";
	path = "/usr/local/jails/vault/vault-churchcrm";

	allow.raw_sockets = 0;
	allow.sysvipc = 0;
	allow.mount = 0;
	allow.mount.devfs = 0;
	enforce_statfs = 2;

	# Only mount the encrypted data directory
	mount.fstab = "/etc/fstab.vault-churchcrm";

	exec.start = "/bin/sh /etc/rc";
	exec.stop = "/bin/sh /etc/rc.shutdown";
	exec.consolelog = "/var/log/jail/vault_churchcrm_console.log";
	persist;
}
