browser {
	host.hostname = "browser.parishbsd.local";
	path = "/usr/local/jails/app/browser";

	vnet;
	vnet.interface = "epair0b";
	exec.prestart = "ifconfig epair0 create up; ifconfig bridge0 addm epair0a up;";
	exec.start = "ifconfig epair0b 10.0.0.2/24 up; route add default 10.0.0.1; /bin/sh /etc/rc";
	exec.poststop = "ifconfig epair0a deletem epair0a; ifconfig epair0a destroy";

	# Xpra socket directory, bind-mounted from the host
	mount.fstab = "/etc/fstab.browser";

	#exec.stop = "/bin/sh /etc/rc.shutdown";
	exec.consolelog = "/var/log/jail_browser_console.log";
	persist;
}
