browser {
	host.hostname = "browser.parishbsd.local";
	path = "/usr/local/jails/app/browser";

	vnet;
	vnet.interface = "epair0b";
	exec.prestart = "ifconfig epair0 create";
	exec.prestart += "ifconfig bridge0 addm epair0a";
	exec prestart += "ifconfig epair0a up";
	exec.poststop = "ifconfig epair0a destroy";

	# Xpra socket directory, bind-mounted from the host
	mount.fstab = "/etc/fstab.browser";

	exec.start = "/bin/sh /etc/rc";
	exec.stop = "/bin/sh /etc/rc.shutdown";
	exec.consolelog = "/var/log/jail_browser_console.log";
	persist;
}
