PERSONALITY_NAME="app-xra"
PERSONALITY_TIER="app"
PERSONALITY_TEMPLATE="zroot/jails/templates/app@base"
PERSONALITY_PACKAGES=""
PERSONALITY_NEEDS_XPRA_DIR="yes"
PERSONALITY_ENCRYPTED_DATA="no"
PERSONALITY_PROVISION=""
